### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by nandparticles** [Claudemirovsky/extension-builder#4]
Error log 

`Run gradle/gradle-build-action@v2
Restore Gradle state from cache
Error: Gradle script '/home/runner/work/extension-builder/extension-builder/gradlew' is not executable.
Error: Gradle script '/home/runner/work/extension-builder/extension-builder/gradlew' is not executable.
    at verifyIsExecutableScript (/home/runner/work/_actions/gradle/gradle-build-action/v2/dist/main/index.js:93966:15)
    at validateGradleWrapper (/home/runner/work/_actions/gradle/gradle-build-action/v2/dist/main/index.js:93952:5)
    at Object.gradleWrapperScript (/home/runner/work/_actions/gradle/gradle-build-action/v2/dist/main/index.js:93945:5)
    at Object.<anonymous> (/home/runner/work/_actions/gradle/gradle-build-action/v2/dist/main/index.js:93885:95)
    at Generator.next (<anonymous>)
    at /home/runner/work/_actions/gradle/gradle-build-action/v2/dist/main/index.js:93875:71
    at new Promise (<anonymous>)
    at __webpack_modules__.3584.__awaiter (/home/runner/work/_actions/gradle/gradle-build-action/v2/dist/main/index.js:93871:12)
    at Object.executeGradleBuild (/home/runner/work/_actions/gradle/gradle-build-action/v2/dist/main/index.js:93884:12)
    at /home/runner/work/_actions/gradle/gradle-build-action/v2/dist/main/index.js:94307:33`

**Comment by nandparticles** [comment]
how do i fix this???
